services:
  database:
    image: postgres:alpine
    restart: always
    environment:
        POSTGRES_USER: ${TYPEORM_USER}
        POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
        POSTGRES_DB: ${TYPEORM_DB}
    volumes:
        - ./pgdata:/var/lib/postgresql/data
    ports:
        - ${TYPEORM_PORT}:${TYPEORM_PORT}
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./src:/app/src
    depends_on:
      - database
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      API_PORT: ${API_PORT}
      JWT_SECRET: ${JWT_SECRET}
      TYPEORM_CONNECTION: ${TYPEORM_CONNECTION}
      TYPEORM_USER: ${TYPEORM_USER}
      TYPEORM_PASSWORD: ${TYPEORM_PASSWORD}
      TYPEORM_DB: ${TYPEORM_DB}
      TYPEORM_PORT: ${TYPEORM_PORT}
      TYPEORM_HOST: database
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
      MAIL_FROM: ${MAIL_FROM}
      WORK_MAIL: ${WORK_MAIL}
      TELEGRAM_BOT_TOKENL: ${TELEGRAM_BOT_TOKEN}
