services:
  database:
    image: postgres:alpine
    restart: always
    hostname: piybeepdb
    environment:
      POSTGRES_USER: ${TYPEORM_USER}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_DB: ${TYPEORM_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./src:/app/src
      - ./static:/app/dist/static
    depends_on:
      - database
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      TYPEORM_HOST: database
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - database
    ports: 
      - "82:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
