services:
  database:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: ${TYPEORM_USER}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_DB: ${TYPEORM_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./src:/app/src
      - ./static:/app/dist/static
    depends_on:
      - database
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      TYPEORM_HOST: database
